// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.core.Core;
import com.mendix.core.action.user.LoginAction;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserActionListener;
import com.mendix.webui.CustomJavaAction;
import myfirstmodule.implement.CustomLoginAction;

public class SetupCustomLoginAction extends CustomJavaAction<java.lang.Void>
{
	public SetupCustomLoginAction(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.addUserAction(CustomLoginAction.class);

		UserActionListener<LoginAction> loginActionListener = new UserActionListener<>(LoginAction.class) {
			@Override
			public boolean check(LoginAction loginAction) {
				return true;
			}
		};

		loginActionListener.addReplaceEvent(CustomLoginAction.class.getName());
		Core.getListenersRegistry().addListener(loginActionListener);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SetupCustomLoginAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
