// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opentelemetry.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.StatusCode;
import opentelemetry.implement.SpanManager;

public class endSpan extends CustomJavaAction<java.lang.Void>
{
	private final java.lang.String spanId_;
	private final opentelemetry.proxies.SpanStatus status_;

	public endSpan(
		IContext context,
		java.lang.String _spanId_,
		java.lang.String _status_
	)
	{
		super(context);
		this.spanId_ = _spanId_;
		this.status_ = _status_ == null ? null : opentelemetry.proxies.SpanStatus.valueOf(_status_);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		StatusCode success = StatusCode.UNSET;
		if (this.status_ != null) {
			switch (status_) {
			case Success :
				success = StatusCode.OK;
				break;
			case Error:
				success = StatusCode.ERROR;
				break;
			default: 
				success = StatusCode.UNSET;
				break;
			}
			SpanManager.endSpan(spanId_, success);
		}
		else {
			SpanManager.endSpan(spanId_, StatusCode.UNSET);
		}
		return null;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "endSpan";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
